### ISSUE TITLE
QCar GPS doesn't work

### ISSUE THREAD

**Issue by svancjan** [quanser/ACC-Competition-2025#36]
We have a problem with the QCarGPS class on the real QCar2. However, after importing the QCarGPS class, Python prints the following error message.

```bash
from pal.products.qcar import QCarGPS
Traceback (most recent call last):
File "", line 1, in 
File "/home/Quanser/libraries/python/pal/products/qcar.py", line 14, in 
from quanser.devices.exceptions import DeviceError
File "/usr/lib/python3/dist-packages/quanser/devices/init.py", line 3, in 
from .types import LCDTouch, RangingMeasurements, VRPNAnalogMeasurements, VRPNButtonMeasurements, VRPNDialMeasurements, VRPNTrackerMeasurements
File "/usr/lib/python3/dist-packages/quanser/devices/types.py", line 2, in 
from quanser.devices.ffi import ffi
ModuleNotFoundError: No module named 'quanser.devices.ffi'
```

There is also the possibility to use a cartographer without the QCarGPS class. What's the difference between a cartographer and QCarGPS on real QCAr2?

**Comment by jshuquanser** [comment]
The error message is indeed a bug in the quanser-sdk python API. We found the issue and should have a fix by end of day or tomorrow.

**Comment by jsp20** [comment]
@svancjan To address your question "There is also the possibility to use a cartographer without the QCarGPS class. What's the difference between a cartographer and QCarGPS on real QCAr2?" 

Option 1: 
Within ROS 2 you have access to the ros cartography package which uses a /scan topic to generate an occupancy grid representation of the space. If you want to find out more I'd recommend taking a look at this link: https://google-cartographer-ros.readthedocs.io/en/latest/index.html 

The ROS cartography package can be used to estimate the location of the QCar based on occupancy grid being generated in real-time. This is one method for obtaining the pose of the QCar 2 while it moves around the map. The upside of this approach is it gives you the ability of estimating the pose of the QCar in an unknown world. The downside, your pose estimate is highly dependent on the uniqueness of the map and the stability of the pose optimizer used by the cartography package.

Option 2: 
Within the available resources for the QCar we provide an example for estimating the pose of the using the "QCarGPS". The way this works is using the LiDAR data to estimate the pose of the QCar based on a reference LiDAR scan. The upside of using the QCarGPS class is the pose estimate is very accurate with respect to the reference scan. The downside, you need to have a physical map which is exactly the same as the one provided by Quanser. 

On a general note, the cartography package does not need the QCarGPS class. 

Hope this helps

**Comment by jshuquanser** [comment]
Regarding the Python error, we have fixed the issue.
When you start the docker image, please do this:
```
BUILD_ARGS="--no-cache" ./scripts/run_dev.sh /home/$USER/Documents/ACC_Development/Development
```
This will force the docker engine to rebuild the images without cache and the image will pick up the fix.
After doing this once, you would not need to have the `BUILD_ARGS="--no-cache"` anymore.

**Comment by kubanond** [comment]
Hi @jshuquanser , when using the QCarGPS, do i need to setup the QCar object first?
I tried the QCarGPS and QCar object, but i faced those issues.
I was doing this in the docker you provided


```
from pal.products.qcar import QCar
from pal.products.qcar import QCarGPS
qcar = QCar(readMode=0)
car name:  qcar2
board identifier:  0@tcpip://localhost:18960?nagle='off'
The remote peer refused the connection, most likely because no server application was listening for connections
gps = QCarGPS([0,0,0])
Couldn't Connect to GPS Server
```

**Comment by jshuquanser** [comment]
@kubanond Two things:
1. If you're trying to access hardware directly, then you'll need to run those on the host. The docker container was mainly for algorithm development (specifically using ROS), where the host will run all the nodes that access hardware, and the docker container will just make use of the ROS messages that provide the hardware information.
2. Since you're using real hardware, the QCar's `board identifier` should just be `0`. I would imagine the `QCarGPS` is also having trouble because it's using the virtual URI. @jsp20, do you know if QCar and QCarGPS in `pal` default to be virtual? I imagine there should be argument to switch to use real hardware?

**Comment by kubanond** [comment]
Hi @jshuquanser , thanks a lot, i moved outside the docker, but still have problems that the python cant see the quanser package.
I was looking for it and it appears that i have quanser-sdk installed.
I was trying to add the quanser to python path like this
`export PYTHONPATH=/home/nvidia/Documents/Quanser/libraries/python:$PYTHONPATH`
but that did not helped. I looked up the last years car, that we have here and the command above was used there to make it work, however on the qcar received for this year competition the command does not work.


The error
```
nvidia@nvidia:~$ python3.8
Python 3.8.10 (default, Mar 18 2025, 20:04:55) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pal.products.qcar import QCar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nvidia/Documents/Quanser/libraries/python/pal/products/qcar.py", line 14, in <module>
    from quanser.devices.exceptions import DeviceError
ModuleNotFoundError: No module named 'quanser'
>>> 
```

**Comment by jshuquanser** [comment]
@kubanond Hmm....I tried it on my QCar2 and it seemed fine:

![Image](https://github.com/user-attachments/assets/d2b4b69a-2eee-4a10-8980-f641d1e9eee3)

How do you check to see that you have quanser-sdk installed?

Did you run `apt search  quanser-sdk` and `apt search python3-quanser-apis`? What's your output? Mine is this:

![Image](https://github.com/user-attachments/assets/415dc649-5338-4afc-9082-60f520ffdd0d)

**Comment by aakhl097** [comment]
How can I use the pal library in the real car instead of docker to run QCar GPS class for position information?

Based on some of the comments, do I have to open the Isaac docker in the development folder:

      - BUILD_ARGS="--no-cache" ./scripts/run_dev.sh /home/$USER/Documents/ACC_Development/dev,

and then import the library with 'from pal.products.qcar import QCarGPS' in a Python script?

Sorry if my question sounds vague.

**Comment by jsp20** [comment]
> [@kubanond](https://github.com/kubanond) Two things:
> 
> 1. If you're trying to access hardware directly, then you'll need to run those on the host. The docker container was mainly for algorithm development (specifically using ROS), where the host will run all the nodes that access hardware, and the docker container will just make use of the ROS messages that provide the hardware information.
> 2. Since you're using real hardware, the QCar's `board identifier` should just be `0`. I would imagine the `QCarGPS` is also having trouble because it's using the virtual URI. [@jsp20](https://github.com/jsp20), do you know if QCar and QCarGPS in `pal` default to be virtual? I imagine there should be argument to switch to use real hardware?

@kubanond Inside the QCar class there is a flag `IS_PHYSICAL_QCAR`  needs to be initialized before you develop any application. This flag will distinguish between a physical or virtual QCar and correctly configure variables used in the subsequent classes. By default, any class inside `qcar.py ` will assume the device is virtual.

**Comment by ondrejkuban** [comment]
@jsp20 Thanks a lot, i was able to run it, the problem was that the quanser package was installed for python3.9, not for python3.8. Thus after some tinkering with the packages, i was able to run it

**Comment by kodytota** [comment]
Hi @jsp20 , I have problem obtaining lidar data through the QCarGPS. When i initialize GPS, and just try to read data, i get following error:
`python3 qcar_gps_node_v2.py 
[INFO] [1750854669.462252872] [gps_publisher_node]: GPS Publisher Node init start.
GPS Server started.
[INFO] [1750854675.108828507] [gps_publisher_node]: GPS Publisher Node started.
The non-blocking stream is in the process of connecting but is not yet connected. The stream_poll function or Stream Poll block must be invoked with the connect flag to complete the connection.
The non-blocking stream is in the process of connecting but is not yet connected. The stream_poll function or Stream Poll block must be invoked with the connect flag to complete the connection.`

from pal.products.qcar import QCarGPS
self.gps = QCarGPS(initialPose=initial_pose, calibrate=calibrate)
flag = self.gps.readLidar()

Thank you for any info.

**Comment by aakhl097** [comment]
Hi @jsp20, I'm also experiencing an issue a bit similar to @kodytota.  

I can see my car's GPS coordinates only when I run the script on the host machine in the folder path of Documents/ACC_Development/Quanser/libraries. Is that how it's supposed to be?

How can I see GPS coordinates in the docker container?

**Comment by jsp20** [comment]
> Hi [@jsp20](https://github.com/jsp20) , I have problem obtaining lidar data through the QCarGPS. When i initialize GPS, and just try to read data, i get following error: `python3 qcar_gps_node_v2.py [INFO] [1750854669.462252872] [gps_publisher_node]: GPS Publisher Node init start. GPS Server started. [INFO] [1750854675.108828507] [gps_publisher_node]: GPS Publisher Node started. The non-blocking stream is in the process of connecting but is not yet connected. The stream_poll function or Stream Poll block must be invoked with the connect flag to complete the connection. The non-blocking stream is in the process of connecting but is not yet connected. The stream_poll function or Stream Poll block must be invoked with the connect flag to complete the connection.`
> 
> from pal.products.qcar import QCarGPS self.gps = QCarGPS(initialPose=initial_pose, calibrate=calibrate) flag = self.gps.readLidar()
> 
> Thank you for any info.

@kodytota  As I mentioned above please make sure you import `IS_PHYSICAL_QCAR` to ensure the QCar GPS class is configured correctly. Primarily there is a stream server which is initialized differently depending on virtual vs physical QCar configuration. 

If the QCarGPS server has started correctly you should see a printout saying `Connected to a Server successfully.`. 

@kodytota @aakhl097 Please make sure you run the QCar GPS class on the **Host** computer and not inside the docker container. If you need to send the GPS coordinates to a node inside the docker container you could create a ROS publisher (if your implementation is using ROS) or using a TCPIP stream (if you are using a native python implementation).

**Comment by aakhl097** [comment]
@jsp20 so sorry. I tried to run the QCar GPS class on the host machine alongside the native launch file containing the ROS2 nodes by creating a ROS publisher and putting it in the path of ROS2 workspace, but the error below popped up.

"A GPIO is in use by another application. Some applications on Linux-based systems use the old sysfs (/sys/class/gpio) file system for GPIO. If a GPIO is exported it cannot be used by QUARC. Try rebooting the target. Support for the given board type does not appear to be installed. Verify that you have selected the correct card in the HIL Initialize block or hil_open function. No QCar found!"

In addition, the was an error that the calibration files can't be located. I think it's because the angles_new_mat file is located in the folder path of Documents/Quanser/libraries/python instead of the ROS2 workspace.

Do you know how these two errors can be fixed? I'd really appreciate your help.

**Comment by jsp20** [comment]
@aakhl097 

You are seeing this error ` "A GPIO is in use by another application. Some applications on Linux-based systems use the old sysfs (/sys/class/gpio) file system for GPIO. If a GPIO is exported it cannot be used by QUARC. Try rebooting the target. Support for the given board type does not appear to be installed. Verify that you have selected the correct card in the HIL Initialize block or hil_open function. No QCar found!" ` because you are trying to run both the LiDAR node and the QCarGPS at the same time. 

Do not do this... As I mentioned earlier the QCarGPS  class will use the LiDAR to create a pose estimate using a scan match algorithm. If you require the raw lidar data you will need to recreate the '/scan' topic using the LiDAR data coming from the QCarGPS class. 

To address this question: 
`In addition, the was an error that the calibration files can't be located. I think it's because the angles_new_mat file is located in the folder path of Documents/Quanser/libraries/python instead of the ROS2 workspace. ` 

You will need to copy the content of this directory `/home/$USER/Documents/ACC_Development/docker/libraries/python`  into '/home/$USER/Documents/libraries/python' . Inside the `~/.basrch` file you will need to append the PYTHONPATH environment variable with the directory `/home/$USER/Documents/libraries/python' . You should now create the angles_new_mat  file in the correct location.
